### ISSUE TITLE
OCP 4.3 Release Notes Tracker

### ISSUE THREAD

**Issue by ahardin-rh** [openshift/openshift-docs#17796] opened 2019-10-31 18:02 UTC
Please leave comments here for anything that should be highlighted in the 4.3 release notes. Thank you! 

rendered draft of 4.3 release notes: https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html

**Comment by tnozicka** [comment] 2019-11-04 08:20
apps/v1beta1, apps/v1beta2, extensions/v1beta1 (except ingresses) are deprecated in 4.3 (were deprecated upstream for some time) and will be removed in 4.4.  Kubernetes 1.16 (in OCP 4.3) has already disabled serving those, but we have re-enabled it back for 4.3 release.

ref https://jira.coreos.com/browse/WRKLDS-16

According to @smarterclayton we should write a section in docs with "master list of deprecations per release somewhere" and reference it from release notes. cc @bergerhoffer

**Comment by mburke5678** [comment] 2019-11-06 16:20
Kubernetes is upgraded to version 1.16 from version 1.14.
[Kubernetes change log for 1.15](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#kubernetes-v115-release-notes)
[Kubernetes change log for 1.16](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#kubernetes-v1160-release-notes)

**Comment by bobfuru** [comment] 2019-11-07 15:50
**RAW BLOCK VOLUME SUPPORT** (`ocp-4-3-storage-devices`)
iSCSI raw block volumes are now fully supported with OpenShift Container Platform 4.3.

Raw block volumes using Cinder are now in Technology Preview.

In `ocp-4-3-technology-preview` table: 

- "Raw Block with Cinder" moves to TP in 4.3
- "Raw Block with iSCSI" moves from TP (4.2) to GA (4.3)

**Comment by jboxman** [comment] 2019-11-12 17:20
OVN SDN is GA in 4.3. (Was TP.)

**Comment by vikram-redhat** [comment] 2019-11-13 02:07
Auto rotation of certs coming: https://jira.coreos.com/browse/PROD-970?focusedCommentId=144768&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-144768

**Comment by bobfuru** [comment] 2019-11-13 16:24
Open a Support Case from the {product-title} web console.
https://jira.coreos.com/browse/OSDOCS-764

**Comment by s-urbaniak** [comment] 2019-12-03 07:51
Tech Preview "User Workload Monitoring" in OpenShift Monitoring: https://jira.coreos.com/browse/PROD-1827

**Comment by jboxman** [comment] 2019-12-03 21:24
Oh, as it happens, _OVN_ is actually _OVN-Kubernetes Pod network provider_. So any instances of _OVN SDN_ really ought to be _OVN-Kubernetes Pod network provider_.

**Comment by jboxman** [comment] 2019-12-05 02:15
Update: OVN is **not** going to be GA in 4.3. So it will still be Tech Preview.

**Comment by bmcelvee** [comment] 2019-12-09 19:28
DevEx: Samples Operator on Power and Z

The Samples Operator automatically recognizes the cluster architecture during installation and does not install incompatible x86_64 content on Power and Z.

**Comment by bergerhoffer** [comment] 2019-12-10 14:27
The release notes currently say `This release uses Kubernetes 1.16 with CRI-O runtime.` 

Update this somehow to make it clear that the Kubernetes version jumped two versions, from 1.14 to 1.16.

**Comment by bergerhoffer** [comment] 2019-12-10 17:46
You can now encrypt data stored in etcd.  See https://jira.coreos.com/browse/OSDOCS-471.

Related docs on etcd encryption and how to enable are here: https://docs.openshift.com/container-platform/4.3/authentication/encrypting-etcd.html

**Comment by kalexand-rh** [comment] 2019-12-11 18:23
@ahardin-rh, can we add this known issue to the release notes? https://bugzilla.redhat.com/show_bug.cgi?id=1773419

**Comment by Preeticp** [comment] 2019-12-13 13:30
Web console>DEVELOPER PERSPECTIVE
You can now use the Developer Perspective to:

- Create serverless applications, revisions, and split traffic between the revisions. 
- Delete applications and all the components associated with it.
- Assign RBAC permissions to users within a project.
- Bind an application with a service using the binding connector.

**Comment by Preeticp** [comment] 2019-12-13 13:54
Developer experience
Helm
Helm is a package manager for Kubernetes and OpenShift applications. It uses a packaging format called Helm Charts to simplify defining, installing, and upgrading of applications and services.

**Comment by Preeticp** [comment] 2019-12-16 16:52
Developer experience
odo
odo in OpenShift Container Platform 4.3, focuses on the user experience of application deployment. `PushTimeout` has been added as a configurable wait parameter. Both Service Catalog and the creation of components have been improved with extended output and information prompts. With this release, architecture support has been expanded to IBM Z and PowerPC platforms, binaries of which are available for installation.

**Comment by spadgett** [comment] 2019-12-16 17:27
Web Console:

> The OpenShift Container Platform web console now supports Windows Containers.

There were no code changes here. I'm not sure it's worth calling out explicitly for console.

> The new ConsoleProjectLink Custom Resource Definition enables you to launch project-specific applications like ServiceMesh and Quay in context.

It's not a new CRD. It's a new option in the existing `ConsoleLink` CRD.

Quay hasn't added a link yet (and I'm not certain about service mesh). I'd simply say it lets you add project-specific links to the project dashboard.

> You can now open a Red Hat Support case from the web console.

Is it worth mentioning this is available under the help menu in the masthead?

**Comment by bobfuru** [comment] 2019-12-16 18:57
Also under Storage, 

> ### Storage
> **PERSISTENT STORAGE USING iSCSI**
> Persistent volumes using iSCSI, previously in Technology Preview, is now fully supported in OpenShift Container Platform 4.3.
> 
> **RAW BLOCK VOLUME SUPPORT**
> iSCSI raw block volumes are now fully supported with OpenShift Container Platform 4.3.
> 
> Raw block volumes using Cinder are now in Technology Preview.
> 
> In `ocp-4-3-technology-preview` table:
> 
> * "Raw Block with Cinder" moves to TP in 4.3
> * "iSCSI and Raw Block with iSCSI" moves from TP (4.2) to GA (4.3)
> 
> **CSI VOLUME EXPANSION**
> Using the Container Storage Interface (CSI) to expand storage volumes after they have already been created is now enabled by default in Technology Preview.

Also under Storage (before PERSISTENT STORAGE USING iSCSI), add:
**OPENSHIFT CONTAINER STORAGE 4.2
Deploy, manage, monitor, and migrate a Red Hat OpenShift Container Storage 4.2 cluster. Read the Red Hat OpenShift Container Storage 4.2 Release Notes here: https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.2/html/4.2_release_notes/

**Comment by bobfuru** [comment] 2019-12-16 19:17
> Open a Support Case from the {product-title} web console.
> https://jira.coreos.com/browse/OSDOCS-764

Change to "Open a Support Case from the **help menu in** the {product-title} web console."

**Comment by bobfuru** [comment] 2019-12-16 19:19
> Is it worth mentioning this is available under the help menu in the masthead?
Yes, we should add "from the help menu in the OCP web console" (noted in previous comment^^).

**Comment by chao007** [comment] 2019-12-17 07:08
@bobfuru  I filed a bug for release_notes.
https://bugzilla.redhat.com/show_bug.cgi?id=1784279

**Comment by enxebre** [comment] 2019-12-17 08:45
Machine health checks is not TP any more.
A Machine which instance is deleted out of band won't attempt to recreate a new instance any more, they enter a "failed" phase, automated remediation can be enable with a Machine health check.

**Comment by soltysh** [comment] 2019-12-17 09:06
This section:
> The apps/v1beta1, apps/v1beta2, extensions/v1beta1 workload alerts are now deprecated with the introduction of Kubernetes 1.16.

should be expanded to mention `UsingDeprecatedAPIExtensionsV1Beta1` alert which will fire when users are using one of the deprecated APIs. Moreover, these APIs will NOT be available in the next version (4.4) which is why it's critical to migrate those and why this alert.
/cc @tnozicka

**Comment by bparees** [comment] 2019-12-17 20:12
@sichvoge @jcantrill i don't see anything in the release notes about log forwarding.  can you suggest something?

Also the `Technology Preview Tracker` table lists `Fluentd Mux` as being tech preview?  I thought that was dropped from v4?

**Comment by gpei** [comment] 2019-12-18 04:41
>OpenShift Container Platform 4.3 is supported on Red Hat Enterprise Linux 7.6 and later, as well as Red Hat Enterprise Linux CoreOS 4.1.

OCP 4.3 is using RHCOS 4.3

>You must use Red Hat Enterprise Linux CoreOS (RHCOS) for the control plane, or master, machines and can use either RHCOS or Red Hat Enterprise Linux 7.6 for compute, or worker, machines.

To be more precise, it's `Red Hat Enterprise Linux 7.6 and later`

And also in 4.3, we start allowing customer-provisioned VPC & Subnets and the support for deploying internal/private OpenShift clusters for IPI install on AWS/GCP/Azure, I think this could be some new features worth mentioning in `Installation and upgrade` section.

**Comment by cuipinghuo** [comment] 2019-12-19 07:59
https://docs.openshift.com/container-platform/4.3/applications/service_brokers/installing-template-service-broker.html
`Enter openshift-template-service-broker in the Name field and click Create.`

For OCP4.3, should be 

`Enter openshift-template-service-broker in the Name field and openshift.io/cluster-monitoring=true in the Labels field and click Create.`

**Comment by xingxingxia** [comment] 2019-12-19 10:15
> ... workload alerts are now deprecated

Agree to above comment of @soltysh . Besides that, should be: such workload is deprecated, instead of the alerts are deprected

**Comment by xingxingxia** [comment] 2019-12-19 10:20
About section:
> Automatic rotation of certificates
>
> Automated CA rotation will be available in this release in a future z-stream update. This is to allow time for administrators to plan accordingly for their environments.
Do you mean https://issues.redhat.com/browse/OCPPLAN-970 / https://issues.redhat.com/browse/MSTR-457 ? If yes, then to be precise, should state service CA clearer, instead of general CA / certificate. CC @barleyer @marun

**Comment by adambkaplan** [comment] 2019-12-19 15:17
**Operators**

1. Samples operator also has new Prometheus metrics about which imagestreams have failed to import, and if the samples operator has invalid configurations [1].
2. Image registry operator:
  a. Bootstraps itself as `Removed` on Baremetal, vSphere, and RHV platforms. New installations will need to set the operator's state to `Managed` in addition to provisioning storage [2].
  b. Operator will alert if it detects the registry's storage has changed, resulting in possible data loss. [3]

**Tech Preview Table**

Multi-stage Dockerfile builds have been GA since 4.1 (currently marked Tech Preview) [4].

[1] https://issues.redhat.com/browse/DEVEXP-377
[2] https://issues.redhat.com/browse/DEVEXP-419
[3] https://issues.redhat.com/browse/DEVEXP-404
[4] https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-technology-preview

**Comment by xiaojiey** [comment] 2019-12-19 16:17
2 comments:
1. for fips on https://docs.openshift.com/container-platform/4.3/installing/installing-fips.html. The RHCOS version should be 4.3, and Rhel node version should be Rhel 7.6 and Rhel 7.7
2. For the motd message, the motd fot oc login worked now; but for other interactive commands such as oc rsh, oc exec, oc attch, not worked. Not sure if we need to add doc for this part? Thanks.

**Comment by xiaojiey** [comment] 2019-12-23 01:40
I didn't saw any content about the FIPS in the release note. Could you please help to add it? Thanks a lot.

**Comment by emmajiafan** [comment] 2019-12-23 02:21
OperatorSDK
For https://docs.openshift.com/container-platform/4.3/operators/operator_sdk/osdk-getting-started.html The Installing from GitHub release-> Procedure Set the release version variable:
"RELEASE_VERSION=v0.8.0"  The OCP 4.3 release uses v0.12.0, should this example use version "v0.12.0"

**Comment by vikram-redhat** [comment] 2019-12-23 02:22
For Tech Preview Table: https://bugzilla.redhat.com/show_bug.cgi?id=1785992. And perhaps a note about the PTP as a new (tech preview) feature. @lamek

**Comment by huiran0826** [comment] 2019-12-23 02:28
@lamek   I filed a bug for release notes. https://bugzilla.redhat.com/show_bug.cgi?id=1785992

**Comment by liangxia** [comment] 2019-12-23 04:48
"Local Storage Persistent Volumes" is GA in OCP 4.2/4.3
https://bugzilla.redhat.com/show_bug.cgi?id=1786009

**Comment by sheriff-rh** [comment] 2020-01-02 19:15
I'm seeing several comments regarding other sections of documentation. Please know that this issue tracker is specifically regarding the **release notes** for 4.3. Please work with the appropriate team via JIRA or bugzilla to address other documentation concerns. Thank you!

**Comment by wzheng1** [comment] 2020-01-06 03:29
Sorry for late notice, but QE suggests to doc this about how to use Jenkins imagestream in disconnected cluster since ImageContentSourcePolicy is not supported by the registry: https://bugzilla.redhat.com/show_bug.cgi?id=1787978 per https://bugzilla.redhat.com/show_bug.cgi?id=1787112#c6 .

**Comment by ashcrow** [comment] 2020-01-06 16:00
Items missing:
- New FIPS option at install time (in docs already)
- New encryption options (not in docs yet)
- New kernel module build and update process (not in docs yet)

**Comment by sheriff-rh** [comment] 2020-01-06 16:45
Apologies @ashcrow , I did add FIPS however the docs have not been rebuilt to include that merge. I'll ask @vikram-redhat  to assist in refreshing the release notes. 
Commit is here: https://github.com/openshift/openshift-docs/pull/18822/files

**Comment by sjwalter2** [comment] 2020-01-06 20:26
https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html#ocp-4-3-cluster-logging-log-forwarding

It appears there are no corresponding documentation for this new feature. The closest I've found is: https://docs.openshift.com/container-platform/4.3/logging/config/cluster-logging-external.html

But that was in 4.2 as well so I dont think it's applicable.

**Comment by codyhoag** [comment] 2020-01-06 21:19
@sjwalter2 I believe Log Forwarding is still being worked on in #17825. I'll add a link in the release notes to reference that future content. FYI, please see https://github.com/openshift/openshift-docs/issues/17796#issuecomment-570311338 for an explanation for what we're tracking in this particular issue. Thanks!

**Comment by vikram-redhat** [comment] 2020-01-06 23:58
@ashcrow both encryption and kernel module work is being done by @chrisnegus this week so should be coming in docs soon. @codyhoag @sheriff-rh

**Comment by jiajliu** [comment] 2020-01-07 03:32
```
See OpenShift 4.x Upgrades phased roll out for more information on the types of updates and upgrade channels.
```
I did not see any 4.3 channels clarification in "OpenShift 4.x Upgrades phased roll out" (https://access.redhat.com/articles/4495171). Does it means 4.3 will have the same channels and policy as 4.2 or 4.3 update missing? It's better to give a clarify about what/how many the channels used for 4.3.

**Comment by barleyer** [comment] 2020-01-07 06:36
> About section:
> 
> > Automatic rotation of certificates
> > Automated CA rotation will be available in this release in a future z-stream update. This is to allow time for administrators to plan accordingly for their environments.
> 
> Do you mean https://issues.redhat.com/browse/OCPPLAN-970 / https://issues.redhat.com/browse/MSTR-457 ? If yes, then to be precise, should state service CA clearer, instead of general CA / certificate. CC @barleyer @marun

I didnt see this change.

**Comment by fgiloux** [comment] 2020-01-07 06:46
"Because upgrades are published to the channels as they are gradually rolled out to customers based on data from the Red Hat Service Reliability Engineering (SRE) team, you might not immediately see notification in the web console that updates from version 4.2.z to 4.3 are available at initial release." this excerpt in conjunction with "Channels are tied to a minor version of OpenShift Container Platform. For instance, OpenShift Container Platform 4.3 channels will never include an upgrade to a 4.4 release." is confusing. I understand that the updates mentioned in the former excerpt are available in the 4.3 channels and that the cluster admin needs to select  the new channel when available for the upgrade to happen but it is not obvious for the reader.

**Comment by fgiloux** [comment] 2020-01-07 07:03
"Automated CA rotation will be available in this release in a future z-stream update. This is to allow time for administrators to plan accordingly for their environments."
This is a bit short. Any link or description of what is meant by "plan accordingly". 
Also +1 to the previous comments on whether it is only for the service CA as per:
https://issues.redhat.com/browse/OCPPLAN-970?focusedCommentId=144768&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-144768
In this regard 4.2 doc tends to imply that it is already happening during upgrades: https://docs.openshift.com/container-platform/4.2/authentication/certificates/service-serving-certificate.html#understanding-service-serving_service-serving-certificate

**Comment by wsun1** [comment] 2020-01-07 12:51
The following bugs need to be highlighted/documented in release notes as known issues
https://bugzilla.redhat.com/show_bug.cgi?id=1787112
https://bugzilla.redhat.com/show_bug.cgi?id=1753562
https://bugzilla.redhat.com/show_bug.cgi?id=1786314
https://bugzilla.redhat.com/show_bug.cgi?id=1769879
https://bugzilla.redhat.com/show_bug.cgi?id=1788062
https://bugzilla.redhat.com/show_bug.cgi?id=1776811

**Comment by vikram-redhat** [comment] 2020-01-07 13:44
FIPS in RHEL 7 is broken: https://bugzilla.redhat.com/show_bug.cgi?id=1787270

**Comment by vikram-redhat** [comment] 2020-01-07 14:02
https://bugzilla.redhat.com/show_bug.cgi?id=1786993 Upgrade issue needs to be documented and confirmed via QE that the workaround described works.

**Comment by katherinedube** [comment] 2020-01-07 14:36
@kalexand-rh Should we also include a short note around adding support for deploying to share VPC/VNet and also private cluster support within the release nodes?

**Comment by jianzhangbjz** [comment] 2020-01-08 07:05
**OLM**
1, The OLM doesn't work in the OCP with Kuryr SDN enabled.
see: https://bugzilla.redhat.com/show_bug.cgi?id=1786217
2, `oc adm catalog build` and `oc adm catalog mirror` don't work for the restricted cluster. See:
 https://bugzilla.redhat.com/show_bug.cgi?id=1773821

**Comment by jnordell** [comment] 2020-01-08 07:33
https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html#ocp-4-3-about-this-release

`Because only Red Hat Enterprise Linux version 7.6 is supported for compute machines, you must not upgrade the Red Hat Enterprise Linux compute machines to version 8.`

Should be 

`Because only Red Hat Enterprise Linux version 7.6 and later is supported for compute machines, you must not upgrade the Red Hat Enterprise Linux compute machines to version 8.`

**Comment by sichvoge** [comment] 2020-01-08 12:28
*OpenShift Monitoring*

Please move "AUTOMATICALLY REPAIR DAMAGED MACHINES WITH MACHINE HEALTH CHECKING" to the Machine API section.

**Comment by adambkaplan** [comment] 2020-01-08 17:47
**Image Registry operator**

> An alert is sent to help prevent possible data loss when the registry storage has changed.

This is misleading - by the time the alert is fired, the data is probably gone. Customers would need to use an appropriate solution to restore their data from a backup.

I suggest changing this to `An alert is sent when the registry storage has changed, as this could result in data loss.`

**Comment by adambkaplan** [comment] 2020-01-08 17:52
**Samples Operator**

> The Samples Operator also uses Prometheus metrics to gather information about which imagestreams have failed to import, and if the Samples Operator has invalid configurations. An alert is sent to notify the administrator.

Last sentence needs further detail - `An alert is sent if the samples operator has invalid configuration or if any imagestream fails to import`.

**Comment by mburke5678** [comment] 2020-01-08 18:18
New features and enhancements -> Cluster logging

1. Can probably change the title from _Cluster logging log forwarding_ to _Log forwarding_.
2. s/the default log forwarding pipelines/using Fluentd plug-ins

**Comment by duanwei33** [comment] 2020-01-09 03:14
For storage ISCSI: 
In New features and enhancements

> PERSISTENT STORAGE USING ISCSI
> Persistent volumes using iSCSI, previously in Technology Preview, is now fully supported in OpenShift Container Platform 4.3.

So I think "Persistent volumes using iSCSI" maybe need to be added in "Table 1. Technology Preview Tracker"?

**Comment by xiaojiey** [comment] 2020-01-09 03:30
> FIPS in RHEL 7 is broken: https://bugzilla.redhat.com/show_bug.cgi?id=1787270
<xiyuan> @vikram-redhat @kalexand-rh The bug is closed now. Fips function works well.

**Comment by sheriff-rh** [comment] 2020-01-09 15:48
@duanwei33 

> So I think "Persistent volumes using iSCSI" maybe need to be added in "Table 1. Technology Preview Tracker"?

We have **Raw Block iSCSI** listed as GA for 4.3 in the Tech Preview tracker - it's about ten rows up from the bottom.

**Comment by bobfuru** [comment] 2020-01-09 16:38
> @duanwei33
> 
> > So I think "Persistent volumes using iSCSI" maybe need to be added in "Table 1. Technology Preview Tracker"?
> 
> We have **Raw Block iSCSI** listed as GA for 4.3 in the Tech Preview tracker - it's about ten rows up from the bottom.

@sheriff-rh I think @duanwei33 is correct. While we do have Raw Block iSCSI in the table, we don't have general iSCSI support in there (also moved from TP to GA). 

We should change the Feature column from `Raw Block with iSCSI` to Raw Block and Persistent Storage with iSCSI`

**Comment by sheriff-rh** [comment] 2020-01-09 18:23
Perfect, thanks @bobfuru !

**Comment by duanwei33** [comment] 2020-01-10 02:20
> > @duanwei33
> > > So I think "Persistent volumes using iSCSI" maybe need to be added in "Table 1. Technology Preview Tracker"?
> > 
> > 
> > We have **Raw Block iSCSI** listed as GA for 4.3 in the Tech Preview tracker - it's about ten rows up from the bottom.
> 
> @sheriff-rh I think @duanwei33 is correct. While we do have Raw Block iSCSI in the table, we don't have general iSCSI support in there (also moved from TP to GA).
> 
> I have changed the Feature column from `Raw Block with iSCSI` to `Raw Block and Persistent Storage with iSCSI` ([PR 18922](https://github.com/openshift/openshift-docs/pull/18922)).

@bobfuru Thanks for the confirmation, yes, this is what I mean.
@sheriff-rh Thanks well.

**Comment by yapei** [comment] 2020-01-10 07:06
> The new ConsoleProjectLink option in the ConsoleLink Custom Resource Definition lets you add project-specific links to the project dashboard.

The new option for `ConsoleLink` CRD is `NamespaceDashboard` so it should be
```
The new location option `NamespaceDashboard` in the ConsoleLink Custom Resource Definition lets you add project-specific links to the project dashboard.
```

**Comment by huiran0826** [comment] 2020-01-10 09:13
Networking->Configuring network policy
"The Kubernetes v1 NetworkPolicy features are available in OpenShift Container Platform except for egress policy types and IPBlock."

In 4.3, IPBlock is supported in NetworkPolicy with limitation. It supports IPBlock without except clauses. If you create a policy with an ipBlock with an except clause, the sdn pods will log warnings, and the entire ipBlock section of that policy will be ignored. Details please see the link:https://issues.redhat.com/browse/SDN-589

**Comment by sunilcio** [comment] 2020-01-10 10:13
In Technology Preview Features table:
https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html#ocp-4-3-technology-preview

Pod sysctls has comment `See Known issues for current limitations.`
We need to remove this comment as currently there is no known issues with Pod sysctls.

**Comment by racedo** [comment] 2020-01-10 12:10
In Known Issues:
Replace:
When installing OpenStack Storage Platform 15 with self-signed certificates, the clouds.yaml file generated by the installer cannot be used to install OpenShift Container Platform (BZ#1786314).

With:
When installing on Red Hat OpenStack Platform 13 or 16, where the OpenStack endpoints are configured with self-signed TLS certificates the installation will fail ([BZ#1786314](https://bugzilla.redhat.com/show_bug.cgi?id=1786314), [BZ#1769879](https://bugzilla.redhat.com/show_bug.cgi?id=1769879), [BZ#1735192](https://bugzilla.redhat.com/show_bug.cgi?id=1735192)).

**Comment by racedo** [comment] 2020-01-10 12:12
Remove: "Machine-api cannot create workers on OpenStack Storage Platform enviroments installed with self-signed certificates (BZ#1769879)." In known bugs (issue included in SSC fix in my previous comment).

**Comment by racedo** [comment] 2020-01-10 12:29
Replace: 
Machine-api cannot create workers on OpenStack Storage Platform enviroments installed with self-signed certificates (BZ#1769879).
With:
 IPI on OpenStack fails with 'Security group rule already exists' error when OpenStack Neutron is under heavy load (BZ#1769879)

Also, please note that this patch is pending approval for 4.3.0, if it gets approved please remove it completely from the Release Notes. Many thanks!

**Comment by sheriff-rh** [comment] 2020-01-10 14:46
> Also, please note that this patch is pending approval for 4.3.0, if it gets approved please remove it completely from the Release Notes. Many thanks!

We'll do our best to keep a watch for it! Thanks for the input @racedo !

**Comment by racedo** [comment] 2020-01-10 16:07
Please, update the Kuryr CNI entry in table. 
Replace:
4.1: TP 
4.2: TP 
4.3: TP

With:
4.1: -
4.2: -
4.3: GA

**Comment by racedo** [comment] 2020-01-10 16:13
Please, add a section to explain that Kuryr is supported, for example in a Networking section (I don't see one at the moment of writing this comment). It should say something like

Networking
Kuryr CNI support for Red Hat OpenStack Platform 13 and 16

In OpenShift Container Platform version 4.3, you can install a customized cluster on Red Hat OpenStack Platform that uses Kuryr SDN.

@mcurry-rh FYI

**Comment by codyhoag** [comment] 2020-01-10 21:05
>Please, update the Kuryr CNI entry in table.
Replace:
4.1: TP
4.2: TP
4.3: TP
>
>With:
4.1: -
4.2: -
4.3: GA

@racedo our previous release notes (e.g., [4.2](https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-technology-preview) and [4.1](https://docs.openshift.com/container-platform/4.1/release_notes/ocp-4-1-release-notes.html#ocp-4-1-technology-preview)) have the Kuryr CNI entry in the table as TP dating back to 3.11. Should those entries be removed? We also have the [Kuryr installation guide](https://docs.openshift.com/container-platform/4.2/installing/installing_openstack/installing-openstack-installer-kuryr.html) published for 4.2 as TP at the moment, so shouldn't it at least be TP for 4.2? Or am I misunderstanding?

**Comment by racedo** [comment] 2020-01-11 10:16
> @racedo our previous release notes (e.g., [4.2](https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-technology-preview) and [4.1](https://docs.openshift.com/container-platform/4.1/release_notes/ocp-4-1-release-notes.html#ocp-4-1-technology-preview)) have the Kuryr CNI entry in the table as TP dating back to 3.11. Should those entries be removed? We also have the [Kuryr installation guide](https://docs.openshift.com/container-platform/4.2/installing/installing_openstack/installing-openstack-installer-kuryr.html) published for 4.2 as TP at the moment, so shouldn't it at least be TP for 4.2? Or am I misunderstanding?

My mistake, 4.2 *is* TP but 3.11 is GA so it's:
3.11: GA
4.1: -
4.2: TP
4.3: GA

Thanks.

**Comment by emmajiafan** [comment] 2020-01-13 02:57
Operator SDK
1. The operatorsdk  release version for ocp 4.3 is 0.12.0 but the doc of ocp 4.3 is still 0.8.0. I comment it before but the comment is hidden now . And there are a lot of errors becasue of this version changed.
The bugs link:
https://bugzilla.redhat.com/show_bug.cgi?id=1787979
https://bugzilla.redhat.com/show_bug.cgi?id=1788008
https://bugzilla.redhat.com/show_bug.cgi?id=1787999
https://bugzilla.redhat.com/show_bug.cgi?id=1787984
https://bugzilla.redhat.com/show_bug.cgi?id=1787986
https://bugzilla.redhat.com/show_bug.cgi?id=1788023
https://bugzilla.redhat.com/show_bug.cgi?id=1788000
https://bugzilla.redhat.com/show_bug.cgi?id=1787980

**Comment by codyhoag** [comment] 2020-01-15 15:30
@emmajiafan thank you for listing those documentation bugs. Please work with the tech writer on your team to resolve them: https://github.com/openshift/openshift-docs/issues/17796#issuecomment-570311338. If you have any comments/corrections for the [release notes](https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html), please add them here. Thank you!

**Comment by bobfuru** [comment] 2020-01-16 16:18
> > > @duanwei33
> > > > So I think "Persistent volumes using iSCSI" maybe need to be added in "Table 1. Technology Preview Tracker"?
> > > 
> > > 
> > > We have **Raw Block iSCSI** listed as GA for 4.3 in the Tech Preview tracker - it's about ten rows up from the bottom.
> > 
> > 
> > @sheriff-rh I think @duanwei33 is correct. While we do have Raw Block iSCSI in the table, we don't have general iSCSI support in there (also moved from TP to GA).
> > I have changed the Feature column from `Raw Block with iSCSI` to `Raw Block and Persistent Storage with iSCSI` ([PR 18922](https://github.com/openshift/openshift-docs/pull/18922)).
> 
> @bobfuru Thanks for the confirmation, yes, this is what I mean.
> @sheriff-rh Thanks well.

@duanwei33 To be extra clear, I broke this into two rows because iSCSI raw block was already GA in 4.2. FYI. (https://github.com/openshift/openshift-docs/pull/19090)

**Comment by duanwei33** [comment] 2020-01-17 00:38
@bobfuru 
I agree to separate them. I will be better to track each of them.
Just one comment for "iSCSI raw block", seems it is TP in 4.2 and turn to GA in 4.3. Correct me if we have other stories behind.  

In 4.2, Raw Block with iSCSI is marked as TP:
https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-technology-preview

In 4.3, it mentioned as "iSCSI raw block volumes are now fully supported with OpenShift Container Platform 4.3.", I guess it also means change from TP.
https://docs.openshift.com/container-platform/4.3/release_notes/ocp-4-3-release-notes.html#ocp-4-3-raw-block-volume

> @duanwei33 To be extra clear, I broke this into two rows because iSCSI raw block was already GA in 4.2. FYI. (#19090)

**Comment by bobfuru** [comment] 2020-01-17 16:06
> In 4.3, it mentioned as "iSCSI raw block volumes are now fully supported with OpenShift Container Platform 4.3.", I guess it also means change from TP.

Thanks - good point, @duanwei33. I added similar wording to this ("previously in Technology Preview"): https://github.com/openshift/openshift-docs/pull/19124

**Comment by duanwei33** [comment] 2020-01-19 01:29
> > In 4.3, it mentioned as "iSCSI raw block volumes are now fully supported with OpenShift Container Platform 4.3.", I guess it also means change from TP.
> 
> Thanks - good point, @duanwei33. I added similar wording to this ("previously in Technology Preview"): #19124

@bobfuru Thanks for the update, looks nice for me, no comments for iSCSI part :)

**Comment by liangxia** [comment] 2020-01-19 02:59
@bobfuru  for raw block with iSCSI, https://bugzilla.redhat.com/show_bug.cgi?id=1792676

**Comment by sheriff-rh** [comment] 2020-01-27 17:48
This tracker is now closed. If further 4.3 release notes input is required, please file an [issue](https://github.com/openshift/openshift-docs/issues/new). Thanks!

**Closed by sheriff-rh** 2020-01-27 17:48 UTC
