### ISSUE TITLE
[enterprise-4.11] Issue in file nodes/nodes/nodes-nodes-resources-configuring.adoc

### ISSUE THREAD

**Issue by ThomasJou** [openshift/openshift-docs#51045] opened 2022-09-29 15:01 UTC
### Which section(s) is the issue in?

I feel like there is a copy paste issue 
your are speaking about [small-node ](custom-kubelet: small-pods) in Automatically allocating 

### What needs fixing?
this should be in Manually allocating section

**Comment by mburke5678** [comment] 2023-04-05 18:16
Cannot reproduce. Closing. Feel free to reopen with more information on the change to make.

**Closed by mburke5678** 2023-04-05 18:16 UTC
