### ISSUE TITLE
[enterprise-4.6] Issue in file scalability_and_performance/scaling-cluster-monitoring-operator.adoc

### ISSUE THREAD

**Issue by funixz** [openshift/openshift-docs#29690] opened 2021-02-23 18:24 UTC
### What needs fixing?

You're still referencing CNS in this doc page.

**Comment by ahardin-rh** [comment] 2021-03-23 13:44
@funixz Thank you for reporting this issue!

The issue is now addressed in https://github.com/openshift/openshift-docs/pull/30753

**Closed by ahardin-rh** 2021-03-23 13:44 UTC
