### ISSUE TITLE
[enterprise-4.10] Issue in file openshift_images/using-templates.adoc

### ISSUE THREAD

**Issue by B0ndo2** [openshift/openshift-docs#53186] opened 2022-11-28 04:25 UTC
### Which section(s) is the issue in?
Creating an application by using the web console

### What needs fixing?
There is no "Add to Project" in the console in 4.10
it is "+Add"

**Comment by abrennan89** [comment] 2023-04-18 15:52
@B0ndo2 can you please provide a link to the place in the documentation where you are seeing this issue?

**Comment by B0ndo2** [comment] 2023-04-18 15:55
https://docs.openshift.com/container-platform/4.10/applications/creating_applications/odc-creating-applications-using-developer-perspective.html

**Comment by abrennan89** [comment] 2023-04-18 20:21
It looks like it only says "Add to Project" specifically in the docs about JAR files: https://docs.openshift.com/container-platform/4.10/applications/creating_applications/odc-creating-applications-using-developer-perspective.html#odc-deploying-java-applications_odc-creating-applications-using-developer-perspective

It is specifically referring to the "Add to Project" option that comes up when you right-click when in the "Topology" view. The "+Add" view is different to the Topology view. Please see the following image for reference:

![image](https://user-images.githubusercontent.com/40172997/232895783-297ac5b9-c7bd-426e-8b1b-d25435fe7afa.png)

Closing this issue since it's not a bug.

**Closed by abrennan89** 2023-04-18 20:21 UTC
