### ISSUE TITLE
day-2 ops guide should contain suggestion on cert-management

### ISSUE THREAD

**Issue by lichyc** [openshift/openshift-docs#8196] opened 2018-03-19 15:22 UTC
In OCP the self-generated are valid for 2-year only and support have seen plenty of cases due unexpected expired certs. 
Therefore I like to suggest to add recommendations to run the cert-check playbook frequently to avoid surprises and suggest to have a tested plan on how/when to re-deploy certs?

**Comment by dmoessne** [comment] 2018-03-19 15:48
+1

**Comment by bfallonf** [comment] 2018-03-21 00:58
@lichyc @dmoessne I agree with this. I'm planning on moving the certificate content from the Admin Solutions guide to the Day two guide.

Does the information in this topic fulfill the requests? It's currently in the install and config guide:

https://docs.openshift.com/container-platform/3.7/install_config/redeploying_certificates.html

(There's a Configuring Custom Certs topic as well)

**Comment by vikram-redhat** [comment] 2018-04-04 04:41
@lichyc and @dmoessne I am going to close this issue based on Brice's response. If you think the problem is still not solved, can you please reopen and let us know why?

**Closed by vikram-redhat** 2018-04-04 04:41 UTC
