### ISSUE TITLE
[enterprise-4.10] Issue in file monitoring/configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by kanekoh** [openshift/openshift-docs#46482] opened 2022-06-09 02:31 UTC
### Which section(s) is the issue in?

Persistent storage prerequisites

### What needs fixing?

From OCP 4.10, the number of replicas for Alertmanager has changed 3 to 2 *1. 

So that, the following should be fixed 

Make sure you have a persistent volume (PV) ready to be claimed by the persistent volume claim (PVC), one PV for each replica. Because Prometheus has two replicas and Alertmanager has ~~three~~ **two** replicas, you need ~~five~~ four PVs to support the entire monitoring stack. The PVs should be available from the Local Storage Operator. This does not apply if you enable dynamically provisioned storage.

*1: https://github.com/openshift/cluster-monitoring-operator/commit/49960048ab89409fbe70f0c7cbf3b0a53895c681

**Comment by bburt-rh** [comment] 2022-08-05 20:13
@cbremble Please triage

**Comment by cbremble** [comment] 2022-08-09 20:15
@bburt-rh when you get a chance please add monitoring-issue label (I can't add because I can't merge)

**Comment by cbremble** [comment] 2022-08-09 20:18
Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4335

**Comment by cbremble** [comment] 2022-09-12 18:16
> Added to Jira: https://issues.redhat.com/browse/RHDEVDOCS-4335

Actually, that Jira has been closed as a duplicate of this: https://issues.redhat.com/browse/RHDEVDOCS-4349 so this GH issue can be closed as it's captured by an existing Jira issue.

**Closed** 2022-09-12 20:57 UTC
Labels: monitoring-issue

**Comment by bburt-rh** [comment] 2022-10-12 18:12
Closed. The change can be viewed at https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#persistent-storage-prerequisites
