### ISSUE TITLE
[enterprise-4.5] Issue in file applications/quotas/quotas-setting-per-project.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#29593] opened 2021-02-18 21:13 UTC
### Which section(s) is the issue in?
Creating object count quotas

You can create an object count quota for all OpenShift Container Platform standard namespaced resource types, such as BuildConfig, and DeploymentConfig. An object quota count places a defined quota on all standard namespaced resource types.

When using a resource quota, an object is charged against the quota if it exists in server storage. These types of quotas are useful to protect against exhaustion of storage resources.

### What needs fixing?
Creating object count quotas

You can create an object count quota for all OpenShift Container Platform standard namespaced resource types, such as BuildConfig, and DeploymentConfig. An object quota count places a defined quota on all standard namespaced resource types.

When using a resource quota, an object is charged against the quota upon creation. These types of quotas are useful to protect against exhaustion of resources. It can only be created if there enough spare resource within the project.

**Comment by ahardin-rh** [comment] 2021-03-30 14:57
@esimim Thank you for reporting this issue! The issue is now addressed in https://github.com/openshift/openshift-docs/pull/31061

**Closed by ahardin-rh** 2021-03-30 14:57 UTC
Labels: issue-burndown
