### ISSUE TITLE
Wrong name of _build_cfg.yml file

### ISSUE THREAD

**Issue by php-coder** [openshift/openshift-docs#1309] opened 2015-12-09 10:57 UTC
In `Contribute to OpenShift documentation` document, section [How it all comes together](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/contributing.adoc#how-it-all-comes-together) contains wrong name of `_build_cfg.yml` file:

>The documentation build system reads the build_cfg.yml metadata file to construct the content from the source files and publish to the relevant product site at https://docs.openshift.com. The build system only reads this file to determine which topic files to include. Therefore, all new topics that are created must be included in the build_cfg.yml metadata file in order to be processed by the build system.

We should replace `build_cfg.yml` by `_build_cfg.yml`

**Comment by php-coder** [comment] 2015-12-09 11:02
I see (here)[https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/contributing.adoc#metadata-file-format] also wrong record separator: it should be 3 dashes, not one:

>-(1)
>Name: Origin of the Species (2)
>Dir:  origin_of_the_species (3)

**Comment by adellape** [comment] 2015-12-09 19:45
@php-coder Thanks. The content was correct in the source, but wasn't rendering as intended. I've addressed in https://github.com/openshift/openshift-docs/pull/1314.

**Closed** 2015-12-09 19:51 UTC
