### ISSUE TITLE
Routes in the core concepts gives me a 404

### ISSUE THREAD

**Issue by themidnightfox** [openshift/openshift-docs#7162] opened 2018-01-16 09:34 UTC
The 'Routes' link in the following page gives me a 404:

Found here: https://docs.openshift.com/container-platform/3.7/architecture/core_concepts/index.html

This gives a 404: https://docs.openshift.com/container-platform/3.7/architecture/core_concepts/routes.html#architecture-core-concepts-routes

**Comment by tmorriso-rh** [comment] 2018-01-30 20:14
Duplicate of https://github.com/openshift/openshift-docs/issues/6491.

**Closed by tmorriso-rh** 2018-01-30 20:14 UTC
Labels: to_followup
