### ISSUE TITLE
[enterprise-4.8] Issue in file operators/admin/olm-upgrading-operators.adoc

### ISSUE THREAD

**Issue by borball** [openshift/openshift-docs#43623] opened 2022-03-22 18:37 UTC
### Which section(s) is the issue in?

Manually approving a pending Operator upgrade

### What needs fixing?

Add the procedure how to approve a pending install plan

**Comment by bergerhoffer** [comment] 2022-09-15 12:23
Marking this as a duplicate of #43622

**Closed by bergerhoffer** 2022-09-15 12:23 UTC
