### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install/disconnected_install.adoc

### ISSUE THREAD

**Issue by blues-man** [openshift/openshift-docs#12442] opened 2018-10-11 14:22 UTC
### Which section(s) is the issue in?
Installing OpenShift Container Platform

### What needs fixing?
```
orge_url=registry.example.com/openshift3/ose-${component}:${version}
```

to

```
oreg_url=registry.example.com/openshift3/ose-${component}:${version}
```

**Comment by vikram-redhat** [comment] 2018-10-12 06:32
@tmorriso-rh - please make sure this issue is not present in older versions and if it is, please apply the fix there as well.

**Comment by vikram-redhat** [comment] 2018-10-12 06:37
Duplicate of https://github.com/openshift/openshift-docs/issues/12353. Closing.

**Closed by vikram-redhat** 2018-10-12 06:37 UTC
