### ISSUE TITLE
[online] Issue in file rosa_support/rosa-troubleshooting-iam-resources.adoc

### ISSUE THREAD

**Issue by faldanarh** [openshift/openshift-docs#47450] opened 2022-07-06 03:07 UTC
### Which section(s) is the issue in?
Troubleshooting IAM roles > Resolving issues with ocm-roles and user-role IAM resources

### What needs fixing?
At the first 'Procedure', the second command must be:
$ rosa list user-role 
Instead of:
$ rosa list ocm-role

**Comment by bergerhoffer** [comment] 2022-09-13 20:34
Closing this as a duplicate of #49322

Thanks for reporting!

**Closed by bergerhoffer** 2022-09-13 20:34 UTC
