### ISSUE TITLE
[enterprise-3.10] Edit suggested in file install/example_inventories.adoc

### ISSUE THREAD

**Issue by jsm84** [openshift/openshift-docs#11507] opened 2018-08-10 20:20 UTC
### Which section(s) is the issue in?
* Multiple Masters Using Native HA with External Clustered etcd

### What needs fixing?
There is a reference to 3.9 which should read 3.10

**Comment by vikram-redhat** [comment] 2018-08-12 08:57
@jsm84 - thanks for filing this. I looked here: https://docs.openshift.com/container-platform/3.10/install/example_inventories.html#multi-masters-using-native-ha-ai and I can't see the issue.

I am going to close it, but please feel free to reopen if you can point to the exact area where the issue is.

**Closed by vikram-redhat** 2018-08-12 08:57 UTC
