### ISSUE TITLE
Implement conscious language into the documentation for "oc adm prune groups"

### ISSUE THREAD

**Issue by tonejito** [openshift/openshift-docs#54883] opened 2023-01-18 19:07 UTC
### Which section(s) is the issue in?

Documentation > OpenShift Container Platform > 4.11 > CLI tools OpenShift CLI (oc) > OpenShift CLI administrator command reference > `oc adm prune groups`

> [1] https://docs.openshift.com/container-platform/4.11/cli_reference/openshift_cli/administrator-cli-commands.html#oc-adm-prune-groups

### What needs fixing?

The command line options of the `oc adm prune groups` [1] command still have the **whitelist** / **blacklist** terms. Red Hat has committed to apply changes in order to eliminate the use of these terms in the docummentation [2] [3].

> [1] https://docs.openshift.com/container-platform/4.11/cli_reference/openshift_cli/administrator-cli-commands.html#oc-adm-prune-groups

```
# Prune all orphaned groups except the ones from the blacklist file
oc adm prune groups --blacklist=/path/to/blacklist.txt --sync-config=/path/to/ldap-sync-config.yaml --confirm
```

```
# Prune all orphaned groups from a list of specific groups specified in a whitelist file
oc adm prune groups --whitelist=/path/to/whitelist.txt --sync-config=/path/to/ldap-sync-config.yaml --confirm
```

References:

> [2] https://www.redhat.com/en/blog/update-red-hats-conscious-language-efforts

> [3] https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language

--------

Replaces: https://github.com/openshift/oc/issues/1303

**Comment by tonejito** [comment] 2023-01-18 19:07
XREF: https://chat.google.com/room/AAAAagA7kdc/hmBi50MOT5o

**Comment by kalexand-rh** [comment] 2023-02-10 17:12
This content is generated from source. Please reopen your issue in openshift/oc. After the issue is fixed in source, the next time we regenerate the CLI docs, the change will be implemented.

**Closed by kalexand-rh** 2023-02-10 17:12 UTC

**Comment by tonejito** [comment] 2023-02-11 00:52
OK, I'll reopen https://github.com/openshift/oc/issues/1303.

Thanks

**Comment by tonejito** [comment] 2023-02-11 00:54
OK, I'll reopen https://github.com/openshift/oc/issues/1303

Thanks

**Comment by tonejito** [comment] 2023-02-11 00:58
Issue reopened

- https://github.com/openshift/oc/issues/1303#issuecomment-1426542688
