### ISSUE TITLE
In quick installation mention the packages requeired before install

### ISSUE THREAD

**Issue by jkaurredhat** [openshift/openshift-docs#683] opened 2015-07-03 10:00 UTC
Before running $ sh <(curl -s https://install.openshift.com/ose/) it is required to install 2 packages as below:

yum install python-virtualenv
yum install gcc

Which aren't mentioned in the quick installation guide. We should mention it as the user will face the issue and then to rectify it he will follow the steps.

**Comment by munchee13** [comment] 2015-07-06 11:31
Can you provide your logs? Not able to reproduce this...

**Comment by jkaurredhat** [comment] 2015-07-06 11:41
See the installation will exit at the start only because the necessary packages( python-virtualenv, gcc ) to run that script are not there. 

Hence this will not even be captured in the install logs as the install script wasn't run.

If you remove the above packages( python-virtualenv,gcc) from your end and run as below 

sh <(curl -s https://install.openshift.com/ose/)

You will surely face an error

**Comment by munchee13** [comment] 2015-07-06 12:01
I added it to my install guide, but mine is not official. This issue should be written against the official install guide.

**Comment by adellape** [comment] 2015-07-09 21:30
Dupe, closing in favor of https://github.com/openshift/openshift-docs/issues/686.

**Closed by adellape** 2015-07-09 21:30 UTC
Labels: enhancement
