### ISSUE TITLE
[enterprise-4.5] Issue in file applications/deployments/route-based-deployment-strategies.adoc

### ISSUE THREAD

**Issue by esimim** [openshift/openshift-docs#29586] opened 2021-02-18 18:59 UTC
### Which section(s) is the issue in?
One service, multiple DeploymentConfig objects
Procedure

    Create a new application, adding a label ab-example=true that will be common to all shards:

    $ oc new-app openshift/deployment-example --name=ab-example-a

    The application is deployed and a service is created. This is the first shard.

### What needs fixing?
One service, multiple DeploymentConfig objects
Procedure

    Create a new application, adding a label ab-example=true that will be common to all shards:

    $ oc new-app openshift/deployment-example --name=ab-example-a --labels=ab-example=true

    The application is deployed and a service is created. This is the first shard.

**Comment by bergerhoffer** [comment] 2021-03-24 12:45
Closing this issue as a duplicate of #29111.

**Closed by bergerhoffer** 2021-03-24 12:45 UTC
Labels: issue-burndown
