### ISSUE TITLE
local persistent storage docs fix

### ISSUE THREAD

**Issue by akostadinov** [openshift/openshift-docs#8670] opened 2018-04-10 20:12 UTC
Hi, this is a copy of https://github.com/openshift/origin/issues/19212

Basically there is a missing step for creating storage classes in the [docs](https://docs.openshift.com/container-platform/3.7/install_config/configuring_local.html). After one goes through the steps in the document, local storage is sitll not working as expected until the necessary storage classes are created. The necessary storage classes are kindly provided by @toni-moreno and @sbengo in https://github.com/openshift/origin/issues/19212#issuecomment-379249805

### What needs fixing?
Add a section for creating the necessary storage classes.

**Comment by vikram-redhat** [comment] 2018-04-11 07:03
@tmorriso-rh - PTAL.

**Comment by tmorriso-rh** [comment] 2018-04-12 19:01
jhou@ | lxia@
@jhou1 @liangxia Please provide the QE review for this PR.

**Comment by jhou1** [comment] 2018-04-13 01:37
@qinpingli PTAL.

**Comment by qinpingli** [comment] 2018-04-13 02:36
The issue is when the openshift users tried to use local volume, they can not select select storageclass for local volume, right?

Yes, now we have this issue.
1) When local storage provisioner creates local PV, it will tag PVs with storageclass name defined in configmap(e.g. this PV is a hdd storage or ssd storage).
2) Openshift users can request storage they needed by storageclassname.
3) But the storageclass name defined in configmap can not be find by "oc get sc|storageclassname" command.
4) So, the web UI can not get storageclass name when creating PVC. The storageclass must be created manually.

**Comment by liangxia** [comment] 2018-04-13 03:30
> But the storageclass name defined in configmap can not be find by "oc get sc|storageclassname" command.

This sounds like a bug.

**Comment by jsafrane** [comment] 2018-04-16 12:48
That's not a bug, it's intention. You can set `pv.spec.storageClassName` without creating a StorageClass object for it. Either you don't need a StorageClass (they're required for dynamic provisioning, otherwise they're optional) or you'll create one later.

I admit it's confusing to users and we should update our docs with creation of StorageClasses.

**Comment by akostadinov** [comment] 2018-04-16 14:10
Also original bug describes a SELinux labeling issue. Any `chcon` needs to be documented unless this is no longer needed with 3.9+.

**Comment by qinpingli** [comment] 2018-04-17 01:55
@akostadinov this was fixed in OCP 3.9 doc.
https://docs.openshift.com/container-platform/3.9/install_config/configuring_local.html

**Comment by tmorriso-rh** [comment] 2018-04-17 18:17
@qinpingli @jsafrane Does this require an update to the docs, or can I close the PR? Thanks.

Cc: @vikram-redhat

**Comment by qinpingli** [comment] 2018-04-18 01:47
I think it still needs an update in the doc for storageclasses creation.

**Comment by vikram-redhat** [comment] 2018-05-09 10:49
@tmorriso-rh - was a PR created to fix?

**Comment by tmorriso-rh** [comment] 2018-05-17 14:31
@akostadinov I am working on this request. Does this apply to all version of OpenShift?

**Comment by qinpingli** [comment] 2018-05-21 01:45
@tmorriso-rh you mean the PR "Add necessary storage classes"? It's worked from openshift 3.7.

**Comment by jsafrane** [comment] 2018-05-21 07:28
Local storage was tech preview also in 3.7. IMO, the best would be to merge https://github.com/openshift/openshift-docs/commit/92cc919d13cafc9383235a6f2d2f293d3f1cc66d into 3.7 to add note about SELinux + add note about StorageClass into 3.7 - 3.10.

**Comment by tmorriso-rh** [comment] 2018-05-30 18:13
Fixed via the following PRs:

https://github.com/openshift/openshift-docs/pull/9540
https://github.com/openshift/openshift-docs/pull/9541

**Closed by tmorriso-rh** 2018-05-30 18:13 UTC
Labels: to_followup

**Comment by benjaminhiggins** [comment] 2018-06-25 20:01
I've tried the new and the old document but I must be missing something. When I add a pvc with the storage class I get the following error:

3:56:33 PM | Warning | Provisioning Failed | no volume plugin matched

Any ideas?

**Comment by jsafrane** [comment] 2018-07-03 16:56
@benjaminapetersen, that looks like a different issue. Your PVC did not match any PV and there is no dynamic provisioning for local storage.

Please double check that local storage provisioner created PVs for your volumes and open a new issue and provide:

- `oc get sc -o yaml`
- `oc get pvc -o yaml <your PVC>`
- `oc describe pvc <your PVC>` (to get the events
- `oc get pv` (to get existing local PVs)
- `oc describe pod <local provisioner pod on a node with local volumes>`
- `oc logs <local provisioner pod on a node with local volumes>`
- ConfigMap with local storage provisioning configuration

**Comment by akostadinov** [comment] 2018-07-03 17:42
The question is whether PV creation is in the document. The original issue was that local storage didn't contain all necessary information to get user started. So if PV creation info is not there, then we need to get it there.
