### ISSUE TITLE
Pre within tables don't wrap on mobile

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-docs#2613] opened 2016-08-07 02:57 UTC
The pre tag within the table in /dev_guide/builds.html doesn't wrap so half the table is off the screen (and also unscrollable)

![image](https://cloud.githubusercontent.com/assets/2239920/17460190/321f3816-5c9e-11e6-9198-21b8ec117da0.png)

This could be fixed by setting `white-space: pre-wrap;` but column width may need to be fixed.

**Comment by mburke5678** [comment] 2017-10-04 15:39
Closing as duplicate of https://github.com/openshift/openshift-docs/issues/1793

**Closed by mburke5678** 2017-10-04 15:39 UTC
