### ISSUE TITLE
[enterprise-4.6] Issue in file installing/installing_rhv/installing-rhv-customizations.adoc

### ISSUE THREAD

**Issue by vpagar1** [openshift/openshift-docs#25393] opened 2020-09-10 20:54 UTC
### Which section(s) is the issue in?
Add a section on customization of resources with the IPI installation method by modifying the install-config file before running a create a cluster.

Because of the RHV bug [1863615](https://bugzilla.redhat.com/show_bug.cgi?id=1863615), the only workaround is to use the vmType as server in install-config, so we need to have details in our document on customizing the resosurces like CPU,RAM, vmType etc for the master and worker nodes. 

### What needs fixing?

Add examples about customizing the resources on RHV IPI install-config file, Below upstram document can be refer for more details.
[oVirt Platform Customization](https://github.com/openshift/installer/blob/master/docs/user/ovirt/customization.md#custom-machine-pools)

**Comment by kalexand-rh** [comment] 2020-09-30 20:35
@rolfedh, PTAL?

**Comment by rolfedh** [comment] 2020-09-30 22:10
@kalexand-rh  Sure thing. This is a duplicate of https://issues.redhat.com/browse/OCPRHV-374 which is documented in enterprise-4.6 and closed. The changes are shown here: https://github.com/openshift/openshift-docs/commit/5bed104c844c38f646d176936ef5e92ed6178d8d

**Comment by kalexand-rh** [comment] 2020-10-01 12:05
Thanks, @rolfedh! I'll close this issue.

**Closed by kalexand-rh** 2020-10-01 12:05 UTC
