### ISSUE TITLE
[enterprise-4.10] Issue in file monitoring/configuring-the-monitoring-stack.adoc

### ISSUE THREAD

**Issue by avyas26** [openshift/openshift-docs#49528] opened 2022-08-24 09:33 UTC
### Which section(s) is the issue in?
https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#persistent-storage-prerequisites

### What needs fixing?
Current: Because Prometheus has two replicas and Alertmanager has three replicas, you need five PVs to support the entire monitoring stack. 

Should be updated to: Because Prometheus has two replicas and Alertmanager has *two* replicas, you need *four* PVs to support the entire monitoring stack. 

Reason: Starting with OCP 4.10 there are only two replicas of Alertmanager

Same change will be required for OCP 4.11 branch too.

**Comment by cbremble** [comment] 2022-09-12 14:28
Thanks for submitting this issue. It is a duplicate of: https://github.com/openshift/openshift-docs/issues/46482 and is already represented in our Jira project: https://issues.redhat.com/browse/RHDEVDOCS-4335.

**Comment by bburt-rh** [comment] 2022-09-12 15:30
@avyas26 Closing this as a duplicate of the Jira issue linked in @cbremble's comment above. 

Feel free to reopen the issue if you feel that it's not a duplicate.

**Closed by bburt-rh** 2022-09-12 15:30 UTC

**Comment by bburt-rh** [comment] 2022-10-12 18:13
You can view the fix here: https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#persistent-storage-prerequisites
