### ISSUE TITLE
[enterprise-4.5] Issue in file machine_management/creating-infrastructure-machinesets.adoc

### ISSUE THREAD

**Issue by noefence** [openshift/openshift-docs#24574] opened 2020-08-07 12:57 UTC
### Which section(s) is the issue in?

#infrastructure-moving-registry_creating-infrastructure-machinesets

### What needs fixing?

registry config object is config.imageregistry/cluster and not just config/cluster

**Comment by garbagego** [comment] 2020-08-17 04:31
@noefence [24319](https://github.com/openshift/openshift-docs/pull/24319)

**Comment by garbagego** [comment] 2020-08-17 04:32
Duplicate of #24129

**Comment by sheriff-rh** [comment] 2020-08-18 14:29
Hello,
As @garbagego  pointed out, this is a duplicate issue, which I have merged changes in  #24319.  

These changes are now live on the Red Hat Customer Portal and on docs.openshift.com: 
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html-single/machine_management/index#infrastructure-moving-registry_creating-infrastructure-machinesets
https://docs.openshift.com/container-platform/4.5/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-registry_creating-infrastructure-machinesets

I will be closing this issue at this time. Thank you for bringing this to our attention!

**Closed by sheriff-rh** 2020-08-18 14:29 UTC
Labels: branch/enterprise-4.5
