### ISSUE TITLE
[enterprise-4.9] Issue in file networking/network_policy/creating-network-policy.adoc

### ISSUE THREAD

**Issue by TerryHu82** [openshift/openshift-docs#41244] opened 2022-02-01 05:14 UTC
### Which section(s) is the issue in?
Prerequisites part

### What needs fixing?

remove duplicate sentence:  Your cluster is using a cluster network provider that supports NetworkPolicy objects, such as the OpenShift SDN network provider with mode: NetworkPolicy set. This mode is the default for OpenShift SDN.

because it has already been mentioned at point #1.

**Comment by bergerhoffer** [comment] 2022-02-07 14:46
CC @JoeAldinger 

https://docs.openshift.com/container-platform/4.9/networking/network_policy/creating-network-policy.html

Remove the last prerequisite bullet since it's a near duplicate of the first

**Closed** 2022-03-23 16:47 UTC
