### ISSUE TITLE
[enterprise-3.11] Edit suggested in file install_config/master_node_configuration.adoc

### ISSUE THREAD

**Issue by chuckersjp** [openshift/openshift-docs#14688] opened 2019-05-03 16:23 UTC
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html#master-node-config-advanced-audit

### What needs fixing?
As written, the example code for the Advance Audit features will cause the control plane to fail to come up in 3.11.  I.e.:

`openshift_master_audit_config={"enabled": true, "auditFilePath": "/var/lib/origin/audit-ocp.log", "maximumFileRetentionDays": 14, "maximumFileSizeMegabytes": 500, "maximumRetainedFiles": 5, "policyFile": "/etc/origin/master/adv-audit.yaml", "logFormat":"json"}`

needs to be removed.  The addition of the "policyFile" and "logFormat" items cause issues for the containerized versions of OCP3.11 and this section should be removed.

**Comment by bysnupy** [comment] 2019-05-04 13:37
It seems there is no way to configure the file specified with `policyFile` during initial installation, AFAIK there is no variable to specify the user defined policy file in `ansible playbooks` when OpenShift install. So you mentioned `openshift_master_audit_config` of `advanced audit` is only valid after first installation of `OCP`.

Personally I think it's a issue of installer, because installer should provide the way to configure policy file. For example, installer should also provide similar way like [Configuring Custom Certificates During Installation](https://docs.openshift.com/container-platform/3.11/install_config/certificate_customization.html#ansible-configuring-custom-certificates).

`/path/on/host/to/*-file` on the host is copied to correct path during installation.
~~~
openshift_master_named_certificates=[{"certfile": "/path/on/host/to/crt-file", "keyfile": "/path/on/host/to/key-file", "names": ["public-master-host.com"], "cafile": "/path/on/host/to/ca-file"}]
~~~

**Comment by chuckersjp** [comment] 2019-05-05 01:40
I think I have tried to edit by hand after the fact as well by putting in the policyFile into `/etc/origin/master/master-config.yaml` but that seems to break it as well.  Are we even sure this still works with containerized control plane?

**Comment by bysnupy** [comment] 2019-05-05 02:21
It has worked well for me. In my case I would configure using `ansible playbooks`. And I could not verify any error messages from a api control plane pod. Sometimes control plane pods might be required to restart a few times using `master-restart` for `Running` state.

FYI, my testing env's information is as follows.
I created/placed the `policy file` as sample of docs before running playbooks.

* Version:
~~~
# oc version
oc v3.11.59
kubernetes v1.11.0+d4cacc0
~~~

* inventory file, `openshift_master_audit_config` is same with a sample of docs.
~~~
openshift_master_audit_config={"enabled": true, "auditFilePath": "/var/lib/origin/audit-ocp.log", "maximumFileRetentionDays": 14, "maximumFileSizeMegabytes": 500, "maximumRetainedFiles": 5, "policyFile": "/etc/origin/master/adv-audit.yaml", "logFormat":"json"}
~~~

* `master-config.yaml`
~~~
auditConfig:
  auditFilePath: /var/lib/origin/audit-ocp.log
  enabled: true
  logFormat: json
  maximumFileRetentionDays: 14
  maximumFileSizeMegabytes: 500
  maximumRetainedFiles: 5
  policyFile: /etc/origin/master/adv-audit.yaml
~~~

**Comment by chuckersjp** [comment] 2019-05-06 21:32
I just attempted the same thing and it didn't work for me:

[root@master1 ~]# oc version
oc v3.11.59
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

restart-master api
and
restart-master controller

caused the whole cluster to fail.  Didn't matter how many times I restarted them it just refused to recover.

**Comment by bysnupy** [comment] 2019-05-07 07:13
Thank you for your verifying.

The `policyFile` and `logFormat` has been matched in `kubernetes`(v1.11) configurations with `--audit-policy-file` and `--audit-log-format`[0].
So I think the configuration is valid, you can also verify the related implementations in `OpenShift` [here - audit.go](https://github.com/openshift/origin/blob/release-3.11/vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/audit.go).

Could you check your master api pod logs ?

e.g.> Can you see the following log messages ?
~~~
I0507 06:45:23.084281       1 feature_gate.go:194] feature gates: map[AdvancedAuditing:true]
~~~

[0] [Log Collector Examples](https://v1-11.docs.kubernetes.io/docs/tasks/debug-application-cluster/audit/#log-collector-examples)
~~~
--audit-policy-file=/etc/kubernetes/audit-policy.yaml --audit-log-path=/var/log/kube-audit --audit-log-format=json
~~~

**Comment by chuckersjp** [comment] 2019-05-07 19:49
Brought up the cluster again today and did the following: `journalctl | grep Advanced`

This resulted in the following:

```May 07 19:04:36 master1.3c80.internal dockerd-current[1564]: I0507 19:04:36.451260       1 feature_gate.go:194] feature gates: map[AdvancedAuditing:true]
May 07 19:04:37 master1.3c80.internal dockerd-current[1564]: I0507 19:04:37.653633       1 feature_gate.go:194] feature gates: map[AdvancedAuditing:true]
May 07 19:05:19 master1.3c80.internal dockerd-current[1564]:       --audit-log-format string                                 Format of saved audits. "legacy" indicates 1-line text format for each event. "json" indicates structured json format. Requires the 'AdvancedAuditing' feature gate. Known formats are legacy,json. (default "json")
May 07 19:05:19 master1.3c80.internal dockerd-current[1564]:       --audit-policy-file string                                Path to the file that defines the audit policy configuration. Requires the 'AdvancedAuditing' feature gate. With AdvancedAuditing, a profile is required to enable auditing.
May 07 19:05:19 master1.3c80.internal dockerd-current[1564]:       --audit-webhook-config-file string                        Path to a kubeconfig formatted file that defines the audit webhook configuration. Requires the 'AdvancedAuditing' feature gate.
May 07 19:05:33 master1.3c80.internal dockerd-current[1564]:       --audit-log-format string                                 Format of saved audits. "legacy" indicates 1-line text format for each event. "json" indicates structured json format. Requires the 'AdvancedAuditing' feature gate. Known formats are legacy,json. (default "json")
May 07 19:05:33 master1.3c80.internal dockerd-current[1564]:       --audit-policy-file string                                Path to the file that defines the audit policy configuration. Requires the 'AdvancedAuditing' feature gate. With AdvancedAuditing, a profile is required to enable auditing.
May 07 19:05:33 master1.3c80.internal dockerd-current[1564]:       --audit-webhook-config-file string                        Path to a kubeconfig formatted file that defines the audit webhook configuration. Requires the 'AdvancedAuditing' feature gate.
May 07 19:06:01 master1.3c80.internal dockerd-current[1564]:       --audit-log-format string                                 Format of saved audits. "legacy" indicates 1-line text format for each event. "json" indicates structured json format. Requires the 'AdvancedAuditing' feature gate. Known formats are legacy,json. (default "json")
May 07 19:06:01 master1.3c80.internal dockerd-current[1564]:       --audit-policy-file string  ```

**Comment by bysnupy** [comment] 2019-05-07 23:28
As you can see, `feature gates: map[AdvancedAuditing:true]` message is shown when the advanced audit configuration is enabled. I think the control plane failure may be caused by other reasons.

**Comment by bysnupy** [comment] 2019-05-21 06:24
@chuckersjp  FYI https://github.com/openshift/openshift-ansible/pull/11620 is merged, so you can specify your policy file using `openshift_master_audit_policyfile` when you install first time.

**Comment by chuckersjp** [comment] 2019-05-21 13:48
@bysnupy Cool!  Thanks.  Now we need to get the docs updates as well.  :-)

**Comment by bysnupy** [comment] 2019-05-21 14:16
@chuckersjp yes, I will also create a PR which request update of related sections in the documentation soon. :)

**Comment by bysnupy** [comment] 2019-05-30 13:09
I've updated related documentation here : https://github.com/openshift/openshift-docs/pull/14980.

**Comment by chuckersjp** [comment] 2019-05-30 13:40
Great!  Let me buy you a drink when I am in Tokyo!

**Closed** 2020-06-01 17:22 UTC
