### ISSUE TITLE
Getting Started Guide: Container-Native Storage 3.9 Container-Native Storage for OpenShift Container Platform

### ISSUE THREAD

**Issue by rjgrange** [openshift/openshift-docs#9555] opened 2018-05-23 19:17 UTC
### Which section(s) is the issue in?
4.1/4.2

### What needs fixing?
4.2 appears to be a duplicate of section 4.1

**Comment by tmorriso-rh** [comment] 2018-06-01 14:03
@jarrpa Hi Jose, can you take a look at this issue? 

The issue is that this section:
https://access.redhat.com/documentation/en-us/container-native_storage/3.9/html/container-native_storage_for_openshift_container_platform/chap-documentation-install_upgrade_matrix_red_hat_gluster_storage_container_native_with_openshift_platform-introduction_containerized_rhgs#idm140266797624096

Seems exactly like this section:
https://access.redhat.com/documentation/en-us/container-native_storage/3.9/html/container-native_storage_for_openshift_container_platform/ch04s02

**Comment by khartsoe** [comment] 2018-06-01 14:15
Hi Traci...thank you for inquiring about this. The difference between Section for 4.1 and 4.2 is that 4.1 is the workflow for deploying Container-Native Storage (CNS=shared file storage/converged infrastructure (compute and storage instances scheduled/run from same hardware), and 4.2 is the workflow for deploying Container-Ready Storage (CRS=provision storage from a dedicated Gluster cluster external to the OCP cluster). There are minor differences in the requirements/workflow and we separated these two use cases to help keep the customer focused on their end goal. Hope this helps.

**Comment by jarrpa** [comment] 2018-06-01 14:43
What Ken said. :)

**Comment by tmorriso-rh** [comment] 2018-06-01 14:51
Thanks. I will close this issue.

**Closed by tmorriso-rh** 2018-06-01 14:51 UTC
