### ISSUE TITLE
[enterprise-4.11] Issue in file openshift_images/index.adoc (GOOD FIRST ISSUE)

### ISSUE THREAD

**Issue by ctauchen** [openshift/openshift-docs#50309] opened 2022-09-13 14:34 UTC
### Which section(s) is the issue in?

https://docs.openshift.com/container-platform/4.11/openshift_images/index.html#images-tag_overview-of-images

### What needs fixing?

The code highlighting is different in the _Image tags_ section. Text there is blue. I'd say the code block is missing a source declaration like in other sections.

**Comment by bergerhoffer** [comment] 2022-09-13 19:06
Marking this as a good candidate for Hacktoberfest.

It looks like the code block here is using [source,text] above it, which is a valid option. However I agree that it does look odd compared to the other code blocks on the page (which aren't blue). Those don't define any source language above their code blocks. 

Whoever updates this should either:

- Remove the [source,text] from the code block in the "Image tags" section, or
- Add [source,text] to the other 3 files on this page that have similar code blocks.

I personally would lean toward the second option, since defining a source language is usually desired on code blocks. 

PR to fix this should be submitted against the main branch, and ping me with any questions!

**Comment by bergerhoffer** [comment] 2022-09-14 15:06
Great thanks @aswin2108! Just FYI that I believe you have to wait to open the PR until October in order for it to count toward Hacktoberfest. Thanks for contributing!

**Comment by aswin2108** [comment] 2022-09-16 09:45
When executing ```asciibinder build``` after following all the instructions this is the output I am getting. what am I doing wrong?
![image](https://user-images.githubusercontent.com/72661784/190610216-7cb12e7a-916d-44b4-ab7d-ec2a4aa729f9.png)

**Comment by bergerhoffer** [comment] 2022-09-19 18:09
Hi @aswin2108! I'm not positive just by looking at that what the issue is. Did you install all of the dependencies listed here? https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/tools_and_setup.adoc#install-the-required-software-dependencies-on-a-linux-system

@jeana-redhat Just checking to see if you happen to have any ideas, since I know you've worked some w/ asciibinder issues in the past.

Anyways, even if you don't get asciibinder to work right away, you can still open a PR and we can take care of building the preview for you to verify the change. Thanks!

**Comment by jeana-redhat** [comment] 2022-09-19 18:45
Hey - sadly, I never did get my asciibinder install unscrambled. This appears to be a different issue than the one I hit, but, alas, I am also not familiar with this problem :disappointed:

@aireilly does the podman workaround that you set up work without a Red Hat account? I have no idea about any restrictions/snags with that, but if we can share it publicly that might help get contributors unstuck.

**Comment by bergerhoffer** [comment] 2022-09-19 19:21
@aswin2108 - jeana made a good point to me offline that we do have an automatic preview system that should create a preview for your when you open the PR (takes about 10-15 minutes after you open the PR for a bot to post a comment with the preview link). So again, I'd recommend to move forward with opening your PR and seeing if the preview is generated for you that way and checking it there. Thanks!

**Comment by aireilly** [comment] 2022-09-20 14:39
> Hey - sadly, I never did get my asciibinder install unscrambled. This appears to be a different issue than the one I hit, but, alas, I am also not familiar with this problem disappointed
> 
> @aireilly does the podman workaround that you set up work without a Red Hat account? I have no idea about any restrictions/snags with that, but if we can share it publicly that might help get contributors unstuck.

https://github.com/openshift-cs/docs-builder/tree/main/asciibinder

You would need to create an account on [quay.io](https://quay.io/repository/), but anyone can do that AFAIK

**Comment by aswin2108** [comment] 2022-09-20 17:16
> @aswin2108 - jeana made a good point to me offline that we do have an automatic preview system that should create a preview for your when you open the PR (takes about 10-15 minutes after you open the PR for a bot to post a comment with the preview link). So again, I'd recommend to move forward with opening your PR and seeing if the preview is generated for you that way and checking it there. Thanks!

Thanks for the info. I think I am supposed to open a PR only in October right, or should I test it (by opening and closing it, will it cause any problems)?

**Comment by bergerhoffer** [comment] 2022-09-20 17:21
It won't cause a problem to open a test PR and then close it. But you might have to open a brand new PR in October for it to count for Hacktoberfest. I'm not positive whether a reopened PR would get counted.

**Comment by aswin2108** [comment] 2022-09-25 06:15
@bergerhoffer I did open a pr to test it, but I don't know why it didn't show up in my pr but saw that it happened in some others! What could I do to solve it?

**Comment by bergerhoffer** [comment] 2022-09-26 12:55
@aswin2108 I commented in the PR too, but it looks like the Travis check got stuck (and the preview build won't generated until that passes). I've closed and reopened the PR, which kicked off the Travis check again, and it looks like the preview build is now available :tada:

**Comment by aswin2108** [comment] 2022-09-26 15:47
@bergerhoffer Thanks for looking into it. I will do the real PR in October!

**Comment by bergerhoffer** [comment] 2022-09-26 16:17
Great! Make sure you register for Hacktoberfest too :slightly_smiling_face:

**Comment by aswin2108** [comment] 2022-10-01 18:22
@bergerhoffer can you please check the PR?

**Comment by aswin2108** [comment] 2022-10-02 12:33
@bergerhoffer I made a PR yesterday! Can you please check it!?

**Comment by aswin2108** [comment] 2022-10-02 18:40
Can anyone check it!?

**Comment by bergerhoffer** [comment] 2022-10-03 13:28
Hi @aswin2108! Thanks for opening a PR. Our team doesn't normally work on Saturdays or Sundays. We're taking a look at it now, thanks!

**Closed** 2022-10-03 14:09 UTC
Labels: Hacktoberfest

**Comment by bergerhoffer** [comment] 2022-10-03 14:13
@aswin2108 Your PR has been merged, and this issue has been closed. Thanks again for your contribution!
