### ISSUE TITLE
Footer obscures content when printing

### ISSUE THREAD

**Issue by robin-owen** [openshift/openshift-docs#5734] opened 2017-10-16 19:52 UTC
When printing the latest online documentation, the footer content is malformed and often obscures relevant content on the page. This is readily apparent when generating a print preview or printing the content to a PDF file.

The footer content only appears on the first page being printed.

Attached: [screenshot from 2017-10-16 15-45-45](https://user-images.githubusercontent.com/32545387/31631939-5236cf78-b289-11e7-9f34-263b595d8418.png)

Thank you!

**Comment by vikram-redhat** [comment] 2018-07-18 05:13
I am unable to reproduce this. I am going to close this issue, please create a new issue if this still occurs for you.

**Closed by vikram-redhat** 2018-07-18 05:13 UTC
