### ISSUE TITLE
[enterprise-4.10] Issue in file installing/installing_azure/installing-azure-account.adoc

### ISSUE THREAD

**Issue by yrro** [openshift/openshift-docs#45375] opened 2022-05-05 14:45 UTC
### Which section(s) is the issue in?
Creating a service principal

### What needs fixing?
This command:

```
$ az role assignment create --role "User Access Administrator" \
    --assignee-object-id $(az ad sp list --filter "appId eq '<appId>'" \ 
       | jq '.[0].objectId' -r)
```

Can be written more concisely:

```
$ az role assignment create --role "User Access Administrator" \
  --assignee-object-id $(az ad sp show --id <appId> --query objectId -o tsv)
```

**Comment by bergerhoffer** [comment] 2022-09-14 15:37
Marking this as a good candidate for Hacktoberfest. 

Link: https://docs.openshift.com/container-platform/4.11/installing/installing_azure/installing-azure-account.html#installation-azure-service-principal_installing-azure-account

Any update that removes a use of 'jq' from our docs is good. The prerequisite of installing jq should also be removed. Someone can make this change and submit the PR against main. We'll get QE to verify the new command.

**Comment by apinnick** [comment] 2022-10-18 14:54
@bergerhoffer 
I created a [PR](https://github.com/openshift/openshift-docs/pull/51790). Who should be assigned from QE?

**Comment by bergerhoffer** [comment] 2022-10-18 15:16
@apinnick I'm not sure. @mjpytlak Do you happen to know who a good QE person would be for an Azure installing doc update?

**Comment by mjpytlak** [comment] 2022-10-18 19:14
Sure @apinnick @bergerhoffer. Azure QE for install docs is @MayXuQQ

**Comment by bergerhoffer** [comment] 2022-10-18 19:16
Thanks @mjpytlak!

**Comment by MayXuQQ** [comment] 2022-10-19 15:43
found another doc bug https://issues.redhat.com/browse/OCPBUGS-2575 when review the [PR]( https://github.com/openshift/openshift-docs/pull/51790)

**Comment by apinnick** [comment] 2022-10-25 13:10
Fixed and merged. https://github.com/openshift/openshift-docs/pull/51790

**Closed by apinnick** 2022-10-25 13:10 UTC
Labels: Hacktoberfest

**Comment by mjpytlak** [comment] 2022-10-25 13:21
@bscott-rh I believe this is related to the work you are doing with https://issues.redhat.com/browse/OCPBUGS-2575. Just want to make sure they are only tangentially related and do not actually contradict/conflict with each other.

**Comment by bscott-rh** [comment] 2022-10-25 18:58
@mjpytlak All good - 2575 was closed as a duplicate of https://github.com/openshift/openshift-docs/pull/51790.
