### ISSUE TITLE
Change "oadm" with "oc adm"

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift/openshift-docs#1845] opened 2016-03-31 10:47 UTC
Now that there is a single oc command with adm capabilities built in, it would be good to update the documentation to reflect it.

**Comment by adelton** [comment] 2017-07-14 09:22
The pull request https://github.com/openshift/origin/pull/8313 was closed / retracted because @smarterclayton in https://github.com/openshift/origin/pull/8313#issuecomment-203966425 casted his preference

```
   I would prefer oadm in any admin documentation for now.
```

The problem is, packages like https://github.com/openshift/origin/releases/download/v3.6.0-rc.0/openshift-origin-client-tools-v3.6.0-rc.0-98b3d56-linux-64bit.tar.gz or atomic-openshift-clients-3.6.96-1.git.0.381dd63.el7.x86_64.rpm only seem to ship `openshift-origin-client-tools-v3.6.0-rc.0-98b3d56-linux-64bit/oc` / `/usr/bin/oc`, with `oadm` not available.

Is it time to get rid of `oadm` across the project? Can `oadm` do anything that `oc adm` cannot?

**Comment by adelton** [comment] 2017-07-14 09:39
Ah, so it looks like in http://lists.openshift.redhat.com/openshift-archives/dev/2017-May/msg00013.html we got the green light.

**Comment by adelton** [comment] 2017-07-14 10:05
Giving it a try with https://github.com/openshift/origin/pull/15202.

**Comment by adelton** [comment] 2017-07-14 10:25
And https://github.com/openshift/openshift-docs/pull/4785.

**Comment by adelton** [comment] 2017-08-23 09:42
Could we have this reopened (GitHub does not allow me to do that)?

The change got into openshift/origin via https://github.com/openshift/origin/pull/15202.

But since this issue is against openshift/openshit-docs, we'd still need https://github.com/openshift/openshift-docs/pull/4785 merged, hence this issue should likely still be open.

**Comment by adelton** [comment] 2017-09-07 06:48
@mfojtik, could you please reopen this issue?

**Closed** 2018-01-09 18:49 UTC
